name: alzheimers-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0
  - scikit-learn=1.3.0
  - jupyter=1.0.0
  - notebook=7.0.0
  - ipykernel=6.25.0
  - joblib=1.3.1
  - pip
  - pip:
    - numba==0.57.1
